// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CuratorConfig struct {
	PhotoQueueBucket     string          `protobuf:"bytes,1,opt,name=photo_queue_bucket,json=photoQueueBucket,proto3" json:"photo_queue_bucket,omitempty"`
	PhotoStorageBucket   string          `protobuf:"bytes,2,opt,name=photo_storage_bucket,json=photoStorageBucket,proto3" json:"photo_storage_bucket,omitempty"`
	PhotoMetadataBucket  string          `protobuf:"bytes,6,opt,name=photo_metadata_bucket,json=photoMetadataBucket,proto3" json:"photo_metadata_bucket,omitempty"`
	PhotoMetadataPath    string          `protobuf:"bytes,7,opt,name=photo_metadata_path,json=photoMetadataPath,proto3" json:"photo_metadata_path,omitempty"`
	CameraModels         []*CameraModels `protobuf:"bytes,4,rep,name=camera_models,json=cameraModels,proto3" json:"camera_models,omitempty"`
	ValidLabels          []string        `protobuf:"bytes,5,rep,name=valid_labels,json=validLabels,proto3" json:"valid_labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CuratorConfig) Reset()         { *m = CuratorConfig{} }
func (m *CuratorConfig) String() string { return proto.CompactTextString(m) }
func (*CuratorConfig) ProtoMessage()    {}
func (*CuratorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *CuratorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CuratorConfig.Unmarshal(m, b)
}
func (m *CuratorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CuratorConfig.Marshal(b, m, deterministic)
}
func (m *CuratorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CuratorConfig.Merge(m, src)
}
func (m *CuratorConfig) XXX_Size() int {
	return xxx_messageInfo_CuratorConfig.Size(m)
}
func (m *CuratorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CuratorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CuratorConfig proto.InternalMessageInfo

func (m *CuratorConfig) GetPhotoQueueBucket() string {
	if m != nil {
		return m.PhotoQueueBucket
	}
	return ""
}

func (m *CuratorConfig) GetPhotoStorageBucket() string {
	if m != nil {
		return m.PhotoStorageBucket
	}
	return ""
}

func (m *CuratorConfig) GetPhotoMetadataBucket() string {
	if m != nil {
		return m.PhotoMetadataBucket
	}
	return ""
}

func (m *CuratorConfig) GetPhotoMetadataPath() string {
	if m != nil {
		return m.PhotoMetadataPath
	}
	return ""
}

func (m *CuratorConfig) GetCameraModels() []*CameraModels {
	if m != nil {
		return m.CameraModels
	}
	return nil
}

func (m *CuratorConfig) GetValidLabels() []string {
	if m != nil {
		return m.ValidLabels
	}
	return nil
}

type CameraModels struct {
	ExifModel            string   `protobuf:"bytes,1,opt,name=exif_model,json=exifModel,proto3" json:"exif_model,omitempty"`
	Abbreviation         string   `protobuf:"bytes,2,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CameraModels) Reset()         { *m = CameraModels{} }
func (m *CameraModels) String() string { return proto.CompactTextString(m) }
func (*CameraModels) ProtoMessage()    {}
func (*CameraModels) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *CameraModels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CameraModels.Unmarshal(m, b)
}
func (m *CameraModels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CameraModels.Marshal(b, m, deterministic)
}
func (m *CameraModels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CameraModels.Merge(m, src)
}
func (m *CameraModels) XXX_Size() int {
	return xxx_messageInfo_CameraModels.Size(m)
}
func (m *CameraModels) XXX_DiscardUnknown() {
	xxx_messageInfo_CameraModels.DiscardUnknown(m)
}

var xxx_messageInfo_CameraModels proto.InternalMessageInfo

func (m *CameraModels) GetExifModel() string {
	if m != nil {
		return m.ExifModel
	}
	return ""
}

func (m *CameraModels) GetAbbreviation() string {
	if m != nil {
		return m.Abbreviation
	}
	return ""
}

func init() {
	proto.RegisterType((*CuratorConfig)(nil), "internal.CuratorConfig")
	proto.RegisterType((*CameraModels)(nil), "internal.CameraModels")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0xd3, 0x56, 0xab, 0x4c, 0x69, 0xa2, 0x5b, 0x35, 0x5c, 0x4c, 0x90, 0x13, 0x07, 0x43,
	0x4c, 0x3d, 0x7a, 0x93, 0xab, 0x4d, 0x2c, 0x3e, 0x00, 0x19, 0x60, 0x5b, 0x36, 0x02, 0x8b, 0xdb,
	0xa1, 0xf1, 0xbd, 0x7c, 0x41, 0xc3, 0xb0, 0x35, 0xad, 0xc7, 0xfd, 0xbf, 0xff, 0x9b, 0xcd, 0xce,
	0x82, 0x9b, 0xeb, 0x66, 0xa3, 0xb6, 0x51, 0x6b, 0x34, 0x69, 0x71, 0xa9, 0x1a, 0x92, 0xa6, 0xc1,
	0x2a, 0xf8, 0x19, 0xc3, 0x3c, 0xee, 0x0c, 0x92, 0x36, 0x31, 0x37, 0xc4, 0x23, 0x88, 0xb6, 0xd4,
	0xa4, 0xd3, 0xaf, 0x4e, 0x76, 0x32, 0xcd, 0xba, 0xfc, 0x53, 0x92, 0x37, 0xf2, 0x47, 0xa1, 0x93,
	0x5c, 0x31, 0x59, 0xf7, 0xe0, 0x95, 0x73, 0xf1, 0x04, 0x37, 0x43, 0x7b, 0x47, 0xda, 0xe0, 0xf6,
	0xaf, 0x3f, 0xe6, 0xfe, 0x30, 0xe9, 0x63, 0x40, 0xd6, 0x58, 0xc2, 0xed, 0x60, 0xd4, 0x92, 0xb0,
	0x40, 0xc2, 0x83, 0x32, 0x65, 0x65, 0xc1, 0x70, 0x65, 0x99, 0x75, 0x22, 0x58, 0xfc, 0x73, 0x5a,
	0xa4, 0xd2, 0xbb, 0x60, 0xe3, 0xfa, 0xc4, 0x78, 0x47, 0x2a, 0xc5, 0x0b, 0xcc, 0x73, 0xac, 0xa5,
	0xc1, 0xb4, 0xd6, 0x85, 0xac, 0x76, 0xde, 0x99, 0x3f, 0x09, 0x67, 0xcb, 0xbb, 0xe8, 0xf0, 0xee,
	0x28, 0x66, 0xbc, 0x62, 0x9a, 0xb8, 0xf9, 0xd1, 0x49, 0x3c, 0x80, 0xbb, 0xc7, 0x4a, 0x15, 0x69,
	0x85, 0x59, 0xef, 0x9e, 0xfb, 0x93, 0xd0, 0x49, 0x66, 0x9c, 0xbd, 0x71, 0x14, 0xac, 0xc1, 0x3d,
	0x1e, 0x20, 0xee, 0x01, 0xe4, 0xb7, 0xda, 0x0c, 0xb7, 0xd9, 0x5d, 0x39, 0x7d, 0xc2, 0x5c, 0x04,
	0xe0, 0x62, 0x96, 0x19, 0xb9, 0x57, 0x48, 0x4a, 0x37, 0x76, 0x39, 0x27, 0x59, 0x36, 0xe5, 0x9f,
	0x79, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x60, 0x56, 0x79, 0xa9, 0x01, 0x00, 0x00,
}
