// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	CuratorConfig
	CameraModels
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CuratorConfig struct {
	PhotoQueueBucket   string          `protobuf:"bytes,1,opt,name=photo_queue_bucket,json=photoQueueBucket" json:"photo_queue_bucket,omitempty"`
	PhotoStorageBucket string          `protobuf:"bytes,2,opt,name=photo_storage_bucket,json=photoStorageBucket" json:"photo_storage_bucket,omitempty"`
	PhotoInfoBucket    string          `protobuf:"bytes,3,opt,name=photo_info_bucket,json=photoInfoBucket" json:"photo_info_bucket,omitempty"`
	CameraModels       []*CameraModels `protobuf:"bytes,4,rep,name=camera_models,json=cameraModels" json:"camera_models,omitempty"`
}

func (m *CuratorConfig) Reset()                    { *m = CuratorConfig{} }
func (m *CuratorConfig) String() string            { return proto.CompactTextString(m) }
func (*CuratorConfig) ProtoMessage()               {}
func (*CuratorConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CuratorConfig) GetPhotoQueueBucket() string {
	if m != nil {
		return m.PhotoQueueBucket
	}
	return ""
}

func (m *CuratorConfig) GetPhotoStorageBucket() string {
	if m != nil {
		return m.PhotoStorageBucket
	}
	return ""
}

func (m *CuratorConfig) GetPhotoInfoBucket() string {
	if m != nil {
		return m.PhotoInfoBucket
	}
	return ""
}

func (m *CuratorConfig) GetCameraModels() []*CameraModels {
	if m != nil {
		return m.CameraModels
	}
	return nil
}

type CameraModels struct {
	ExifModel    string `protobuf:"bytes,1,opt,name=exif_model,json=exifModel" json:"exif_model,omitempty"`
	Abbreviation string `protobuf:"bytes,2,opt,name=abbreviation" json:"abbreviation,omitempty"`
}

func (m *CameraModels) Reset()                    { *m = CameraModels{} }
func (m *CameraModels) String() string            { return proto.CompactTextString(m) }
func (*CameraModels) ProtoMessage()               {}
func (*CameraModels) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CameraModels) GetExifModel() string {
	if m != nil {
		return m.ExifModel
	}
	return ""
}

func (m *CameraModels) GetAbbreviation() string {
	if m != nil {
		return m.Abbreviation
	}
	return ""
}

func init() {
	proto.RegisterType((*CuratorConfig)(nil), "config.CuratorConfig")
	proto.RegisterType((*CameraModels)(nil), "config.CameraModels")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xa9, 0x2b, 0x0b, 0x3b, 0x66, 0x51, 0xc3, 0x1e, 0xf6, 0x22, 0x2c, 0x3d, 0x2d, 0x22,
	0x8b, 0xe8, 0xc9, 0xab, 0x3d, 0x79, 0xf0, 0xd0, 0xfa, 0x00, 0x25, 0x89, 0x49, 0x0d, 0xda, 0x4c,
	0x4d, 0x13, 0xf1, 0x49, 0x7d, 0x1e, 0xe9, 0x24, 0x4a, 0xf7, 0x38, 0xff, 0xf7, 0xcd, 0x90, 0x3f,
	0xc0, 0x14, 0x3a, 0x63, 0xbb, 0xc3, 0xe0, 0x31, 0x20, 0x5f, 0xa6, 0xa9, 0xfc, 0x29, 0x60, 0x5d,
	0x45, 0x2f, 0x02, 0xfa, 0x8a, 0x12, 0x7e, 0x03, 0x7c, 0x78, 0xc3, 0x80, 0xed, 0x67, 0xd4, 0x51,
	0xb7, 0x32, 0xaa, 0x77, 0x1d, 0xb6, 0xc5, 0xae, 0xd8, 0xaf, 0x9a, 0x0b, 0x22, 0xf5, 0x04, 0x1e,
	0x29, 0xe7, 0xb7, 0xb0, 0x49, 0xf6, 0x18, 0xd0, 0x8b, 0xee, 0xdf, 0x3f, 0x21, 0x3f, 0x5d, 0x7a,
	0x49, 0x28, 0x6f, 0x5c, 0xc3, 0x65, 0xda, 0xb0, 0xce, 0xe0, 0x9f, 0xbe, 0x20, 0xfd, 0x9c, 0xc0,
	0x93, 0x33, 0x98, 0xdd, 0x07, 0x58, 0x2b, 0xd1, 0x6b, 0x2f, 0xda, 0x1e, 0x5f, 0xf5, 0xc7, 0xb8,
	0x3d, 0xdd, 0x2d, 0xf6, 0x67, 0x77, 0x9b, 0x43, 0xee, 0x52, 0x11, 0x7c, 0x26, 0xd6, 0x30, 0x35,
	0x9b, 0xca, 0x1a, 0xd8, 0x9c, 0xf2, 0x2b, 0x00, 0xfd, 0x6d, 0x4d, 0x3a, 0x94, 0xeb, 0xac, 0xa6,
	0x84, 0x38, 0x2f, 0x81, 0x09, 0x29, 0xbd, 0xfe, 0xb2, 0x22, 0x58, 0x74, 0xf9, 0xfd, 0x47, 0x99,
	0x5c, 0xd2, 0xd7, 0xdd, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x09, 0xf0, 0xff, 0x4a, 0x01,
	0x00, 0x00,
}
