version: v1
runtime: go
api_version: go1

handlers:
- url: /r
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 7d

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /rate
  static_files: static/index.html
  upload: static/index.html
  login: admin

- url: /.*
  script: _go_app
