// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileType int32

const (
	FileType_JPG FileType = 0
	FileType_RAW FileType = 1
)

var FileType_name = map[int32]string{
	0: "JPG",
	1: "RAW",
}

var FileType_value = map[string]int32{
	"JPG": 0,
	"RAW": 1,
}

func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}

func (FileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

type MediaSet struct {
	Media                []*Media `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MediaSet) Reset()         { *m = MediaSet{} }
func (m *MediaSet) String() string { return proto.CompactTextString(m) }
func (*MediaSet) ProtoMessage()    {}
func (*MediaSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *MediaSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaSet.Unmarshal(m, b)
}
func (m *MediaSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaSet.Marshal(b, m, deterministic)
}
func (m *MediaSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaSet.Merge(m, src)
}
func (m *MediaSet) XXX_Size() int {
	return xxx_messageInfo_MediaSet.Size(m)
}
func (m *MediaSet) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaSet.DiscardUnknown(m)
}

var xxx_messageInfo_MediaSet proto.InternalMessageInfo

func (m *MediaSet) GetMedia() []*Media {
	if m != nil {
		return m.Media
	}
	return nil
}

// This represents a single image. It may contain a set of different files for example (.jpg, .raw, .mp4, etc)
// that have different resolutions or image quality for the same image.
type Media struct {
	// This is the "key" that you can use to refer to this image.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// This is the timestamp of when this Media object was last modified. When you modify a media object, don't modify
	// the current one, but just add a new one with a new timestamp.
	TimestampSeconds int64 `protobuf:"varint,2,opt,name=timestamp_seconds,json=timestampSeconds,proto3" json:"timestamp_seconds,omitempty"`
	// Metadata for the image.
	Photo *PhotoInfo `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	// The list of files that represent this image.
	File []*FileInfo `protobuf:"bytes,4,rep,name=file,proto3" json:"file,omitempty"`
	// Normalized name - This is constructed from the image metadata.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Allows us to tag images so we can easily sort and organize.
	Tags                 []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Media) Reset()         { *m = Media{} }
func (m *Media) String() string { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()    {}
func (*Media) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *Media) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Media.Unmarshal(m, b)
}
func (m *Media) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Media.Marshal(b, m, deterministic)
}
func (m *Media) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Media.Merge(m, src)
}
func (m *Media) XXX_Size() int {
	return xxx_messageInfo_Media.Size(m)
}
func (m *Media) XXX_DiscardUnknown() {
	xxx_messageInfo_Media.DiscardUnknown(m)
}

var xxx_messageInfo_Media proto.InternalMessageInfo

func (m *Media) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Media) GetTimestampSeconds() int64 {
	if m != nil {
		return m.TimestampSeconds
	}
	return 0
}

func (m *Media) GetPhoto() *PhotoInfo {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *Media) GetFile() []*FileInfo {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Media) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Media) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// Information about the original media capture, this information shouldn't change.
type PhotoInfo struct {
	// int64 epoch_in_seconds = 1;
	TimestampSeconds     int64     `protobuf:"varint,1,opt,name=timestamp_seconds,json=timestampSeconds,proto3" json:"timestamp_seconds,omitempty"`
	Datetime             string    `protobuf:"bytes,10,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Make                 string    `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model                string    `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Aperture             *Fraction `protobuf:"bytes,4,opt,name=aperture,proto3" json:"aperture,omitempty"`
	ExposureTime         *Fraction `protobuf:"bytes,5,opt,name=exposure_time,json=exposureTime,proto3" json:"exposure_time,omitempty"`
	FocalLength          *Fraction `protobuf:"bytes,6,opt,name=focal_length,json=focalLength,proto3" json:"focal_length,omitempty"`
	Iso                  int32     `protobuf:"varint,7,opt,name=iso,proto3" json:"iso,omitempty"`
	Width                int32     `protobuf:"varint,8,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32     `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PhotoInfo) Reset()         { *m = PhotoInfo{} }
func (m *PhotoInfo) String() string { return proto.CompactTextString(m) }
func (*PhotoInfo) ProtoMessage()    {}
func (*PhotoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *PhotoInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoInfo.Unmarshal(m, b)
}
func (m *PhotoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoInfo.Marshal(b, m, deterministic)
}
func (m *PhotoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoInfo.Merge(m, src)
}
func (m *PhotoInfo) XXX_Size() int {
	return xxx_messageInfo_PhotoInfo.Size(m)
}
func (m *PhotoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoInfo proto.InternalMessageInfo

func (m *PhotoInfo) GetTimestampSeconds() int64 {
	if m != nil {
		return m.TimestampSeconds
	}
	return 0
}

func (m *PhotoInfo) GetDatetime() string {
	if m != nil {
		return m.Datetime
	}
	return ""
}

func (m *PhotoInfo) GetMake() string {
	if m != nil {
		return m.Make
	}
	return ""
}

func (m *PhotoInfo) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *PhotoInfo) GetAperture() *Fraction {
	if m != nil {
		return m.Aperture
	}
	return nil
}

func (m *PhotoInfo) GetExposureTime() *Fraction {
	if m != nil {
		return m.ExposureTime
	}
	return nil
}

func (m *PhotoInfo) GetFocalLength() *Fraction {
	if m != nil {
		return m.FocalLength
	}
	return nil
}

func (m *PhotoInfo) GetIso() int32 {
	if m != nil {
		return m.Iso
	}
	return 0
}

func (m *PhotoInfo) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *PhotoInfo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type FileInfo struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Type                 FileType `protobuf:"varint,2,opt,name=type,proto3,enum=message.FileType" json:"type,omitempty"`
	Md5Sum               []byte   `protobuf:"bytes,3,opt,name=md5sum,proto3" json:"md5sum,omitempty"`
	Sha256Sum            []byte   `protobuf:"bytes,4,opt,name=sha256sum,proto3" json:"sha256sum,omitempty"`
	SizeInBytes          int64    `protobuf:"varint,5,opt,name=size_in_bytes,json=sizeInBytes,proto3" json:"size_in_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileInfo) GetType() FileType {
	if m != nil {
		return m.Type
	}
	return FileType_JPG
}

func (m *FileInfo) GetMd5Sum() []byte {
	if m != nil {
		return m.Md5Sum
	}
	return nil
}

func (m *FileInfo) GetSha256Sum() []byte {
	if m != nil {
		return m.Sha256Sum
	}
	return nil
}

func (m *FileInfo) GetSizeInBytes() int64 {
	if m != nil {
		return m.SizeInBytes
	}
	return 0
}

type Fraction struct {
	Numerator            int32    `protobuf:"varint,1,opt,name=numerator,proto3" json:"numerator,omitempty"`
	Denominator          int32    `protobuf:"varint,2,opt,name=denominator,proto3" json:"denominator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fraction) Reset()         { *m = Fraction{} }
func (m *Fraction) String() string { return proto.CompactTextString(m) }
func (*Fraction) ProtoMessage()    {}
func (*Fraction) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}

func (m *Fraction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fraction.Unmarshal(m, b)
}
func (m *Fraction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fraction.Marshal(b, m, deterministic)
}
func (m *Fraction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fraction.Merge(m, src)
}
func (m *Fraction) XXX_Size() int {
	return xxx_messageInfo_Fraction.Size(m)
}
func (m *Fraction) XXX_DiscardUnknown() {
	xxx_messageInfo_Fraction.DiscardUnknown(m)
}

var xxx_messageInfo_Fraction proto.InternalMessageInfo

func (m *Fraction) GetNumerator() int32 {
	if m != nil {
		return m.Numerator
	}
	return 0
}

func (m *Fraction) GetDenominator() int32 {
	if m != nil {
		return m.Denominator
	}
	return 0
}

// TODO: Remove everything below here, I don't think it is needed any longer.
type PhotoSet struct {
	Photo                []*Photo `protobuf:"bytes,1,rep,name=photo,proto3" json:"photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhotoSet) Reset()         { *m = PhotoSet{} }
func (m *PhotoSet) String() string { return proto.CompactTextString(m) }
func (*PhotoSet) ProtoMessage()    {}
func (*PhotoSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{5}
}

func (m *PhotoSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoSet.Unmarshal(m, b)
}
func (m *PhotoSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoSet.Marshal(b, m, deterministic)
}
func (m *PhotoSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoSet.Merge(m, src)
}
func (m *PhotoSet) XXX_Size() int {
	return xxx_messageInfo_PhotoSet.Size(m)
}
func (m *PhotoSet) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoSet.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoSet proto.InternalMessageInfo

func (m *PhotoSet) GetPhoto() []*Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

type Photo struct {
	Key                  string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Path                 string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	NumBytes             int64                  `protobuf:"varint,3,opt,name=num_bytes,json=numBytes,proto3" json:"num_bytes,omitempty"`
	UserHide             bool                   `protobuf:"varint,5,opt,name=user_hide,json=userHide,proto3" json:"user_hide,omitempty"`
	Md5Sum               []byte                 `protobuf:"bytes,6,opt,name=md5sum,proto3" json:"md5sum,omitempty"`
	Sha256Sum            []byte                 `protobuf:"bytes,7,opt,name=sha256sum,proto3" json:"sha256sum,omitempty"`
	Properties           *Photo_PhotoProperties `protobuf:"bytes,4,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Photo) Reset()         { *m = Photo{} }
func (m *Photo) String() string { return proto.CompactTextString(m) }
func (*Photo) ProtoMessage()    {}
func (*Photo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{6}
}

func (m *Photo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Photo.Unmarshal(m, b)
}
func (m *Photo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Photo.Marshal(b, m, deterministic)
}
func (m *Photo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Photo.Merge(m, src)
}
func (m *Photo) XXX_Size() int {
	return xxx_messageInfo_Photo.Size(m)
}
func (m *Photo) XXX_DiscardUnknown() {
	xxx_messageInfo_Photo.DiscardUnknown(m)
}

var xxx_messageInfo_Photo proto.InternalMessageInfo

func (m *Photo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Photo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Photo) GetNumBytes() int64 {
	if m != nil {
		return m.NumBytes
	}
	return 0
}

func (m *Photo) GetUserHide() bool {
	if m != nil {
		return m.UserHide
	}
	return false
}

func (m *Photo) GetMd5Sum() []byte {
	if m != nil {
		return m.Md5Sum
	}
	return nil
}

func (m *Photo) GetSha256Sum() []byte {
	if m != nil {
		return m.Sha256Sum
	}
	return nil
}

func (m *Photo) GetProperties() *Photo_PhotoProperties {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Photo_PhotoProperties struct {
	EpochInSeconds       int64     `protobuf:"varint,1,opt,name=epoch_in_seconds,json=epochInSeconds,proto3" json:"epoch_in_seconds,omitempty"`
	Width                int32     `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32     `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Make                 string    `protobuf:"bytes,4,opt,name=make,proto3" json:"make,omitempty"`
	Model                string    `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Aperture             *Fraction `protobuf:"bytes,6,opt,name=aperture,proto3" json:"aperture,omitempty"`
	ExposureTime         *Fraction `protobuf:"bytes,7,opt,name=exposure_time,json=exposureTime,proto3" json:"exposure_time,omitempty"`
	FocalLength          *Fraction `protobuf:"bytes,8,opt,name=focal_length,json=focalLength,proto3" json:"focal_length,omitempty"`
	Iso                  int32     `protobuf:"varint,9,opt,name=iso,proto3" json:"iso,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Photo_PhotoProperties) Reset()         { *m = Photo_PhotoProperties{} }
func (m *Photo_PhotoProperties) String() string { return proto.CompactTextString(m) }
func (*Photo_PhotoProperties) ProtoMessage()    {}
func (*Photo_PhotoProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{6, 0}
}

func (m *Photo_PhotoProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Photo_PhotoProperties.Unmarshal(m, b)
}
func (m *Photo_PhotoProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Photo_PhotoProperties.Marshal(b, m, deterministic)
}
func (m *Photo_PhotoProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Photo_PhotoProperties.Merge(m, src)
}
func (m *Photo_PhotoProperties) XXX_Size() int {
	return xxx_messageInfo_Photo_PhotoProperties.Size(m)
}
func (m *Photo_PhotoProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_Photo_PhotoProperties.DiscardUnknown(m)
}

var xxx_messageInfo_Photo_PhotoProperties proto.InternalMessageInfo

func (m *Photo_PhotoProperties) GetEpochInSeconds() int64 {
	if m != nil {
		return m.EpochInSeconds
	}
	return 0
}

func (m *Photo_PhotoProperties) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Photo_PhotoProperties) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Photo_PhotoProperties) GetMake() string {
	if m != nil {
		return m.Make
	}
	return ""
}

func (m *Photo_PhotoProperties) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Photo_PhotoProperties) GetAperture() *Fraction {
	if m != nil {
		return m.Aperture
	}
	return nil
}

func (m *Photo_PhotoProperties) GetExposureTime() *Fraction {
	if m != nil {
		return m.ExposureTime
	}
	return nil
}

func (m *Photo_PhotoProperties) GetFocalLength() *Fraction {
	if m != nil {
		return m.FocalLength
	}
	return nil
}

func (m *Photo_PhotoProperties) GetIso() int32 {
	if m != nil {
		return m.Iso
	}
	return 0
}

type ComparisonEntry struct {
	Photo1 string `protobuf:"bytes,1,opt,name=photo1,proto3" json:"photo1,omitempty"`
	Photo2 string `protobuf:"bytes,2,opt,name=photo2,proto3" json:"photo2,omitempty"`
	// Should only be 1 or 2.
	Score                int32    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComparisonEntry) Reset()         { *m = ComparisonEntry{} }
func (m *ComparisonEntry) String() string { return proto.CompactTextString(m) }
func (*ComparisonEntry) ProtoMessage()    {}
func (*ComparisonEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{7}
}

func (m *ComparisonEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComparisonEntry.Unmarshal(m, b)
}
func (m *ComparisonEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComparisonEntry.Marshal(b, m, deterministic)
}
func (m *ComparisonEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComparisonEntry.Merge(m, src)
}
func (m *ComparisonEntry) XXX_Size() int {
	return xxx_messageInfo_ComparisonEntry.Size(m)
}
func (m *ComparisonEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ComparisonEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ComparisonEntry proto.InternalMessageInfo

func (m *ComparisonEntry) GetPhoto1() string {
	if m != nil {
		return m.Photo1
	}
	return ""
}

func (m *ComparisonEntry) GetPhoto2() string {
	if m != nil {
		return m.Photo2
	}
	return ""
}

func (m *ComparisonEntry) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type Comparison struct {
	Epoch                int64              `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Entry                []*ComparisonEntry `protobuf:"bytes,2,rep,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Comparison) Reset()         { *m = Comparison{} }
func (m *Comparison) String() string { return proto.CompactTextString(m) }
func (*Comparison) ProtoMessage()    {}
func (*Comparison) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8}
}

func (m *Comparison) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comparison.Unmarshal(m, b)
}
func (m *Comparison) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comparison.Marshal(b, m, deterministic)
}
func (m *Comparison) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comparison.Merge(m, src)
}
func (m *Comparison) XXX_Size() int {
	return xxx_messageInfo_Comparison.Size(m)
}
func (m *Comparison) XXX_DiscardUnknown() {
	xxx_messageInfo_Comparison.DiscardUnknown(m)
}

var xxx_messageInfo_Comparison proto.InternalMessageInfo

func (m *Comparison) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Comparison) GetEntry() []*ComparisonEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type ComparisonSet struct {
	Comparison           []*Comparison `protobuf:"bytes,1,rep,name=comparison,proto3" json:"comparison,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ComparisonSet) Reset()         { *m = ComparisonSet{} }
func (m *ComparisonSet) String() string { return proto.CompactTextString(m) }
func (*ComparisonSet) ProtoMessage()    {}
func (*ComparisonSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{9}
}

func (m *ComparisonSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComparisonSet.Unmarshal(m, b)
}
func (m *ComparisonSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComparisonSet.Marshal(b, m, deterministic)
}
func (m *ComparisonSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComparisonSet.Merge(m, src)
}
func (m *ComparisonSet) XXX_Size() int {
	return xxx_messageInfo_ComparisonSet.Size(m)
}
func (m *ComparisonSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ComparisonSet.DiscardUnknown(m)
}

var xxx_messageInfo_ComparisonSet proto.InternalMessageInfo

func (m *ComparisonSet) GetComparison() []*Comparison {
	if m != nil {
		return m.Comparison
	}
	return nil
}

func init() {
	proto.RegisterEnum("message.FileType", FileType_name, FileType_value)
	proto.RegisterType((*MediaSet)(nil), "message.MediaSet")
	proto.RegisterType((*Media)(nil), "message.Media")
	proto.RegisterType((*PhotoInfo)(nil), "message.PhotoInfo")
	proto.RegisterType((*FileInfo)(nil), "message.FileInfo")
	proto.RegisterType((*Fraction)(nil), "message.Fraction")
	proto.RegisterType((*PhotoSet)(nil), "message.PhotoSet")
	proto.RegisterType((*Photo)(nil), "message.Photo")
	proto.RegisterType((*Photo_PhotoProperties)(nil), "message.Photo.PhotoProperties")
	proto.RegisterType((*ComparisonEntry)(nil), "message.ComparisonEntry")
	proto.RegisterType((*Comparison)(nil), "message.Comparison")
	proto.RegisterType((*ComparisonSet)(nil), "message.ComparisonSet")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 752 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x6a, 0xdb, 0x58,
	0x10, 0x5e, 0x59, 0x96, 0x2d, 0x8d, 0x9d, 0xc4, 0x39, 0xbb, 0x2c, 0x22, 0x1b, 0x16, 0x21, 0x76,
	0x41, 0xec, 0xb2, 0x66, 0xd7, 0xd9, 0xe4, 0xb2, 0xd0, 0xff, 0x26, 0xb4, 0x10, 0x4e, 0x02, 0xb9,
	0x34, 0x8a, 0x75, 0x62, 0x89, 0x58, 0x3a, 0x42, 0xe7, 0x98, 0xd6, 0x7d, 0x9c, 0xde, 0xf4, 0x31,
	0x0a, 0x7d, 0x8d, 0xbe, 0x4c, 0x99, 0x39, 0xb2, 0xec, 0x18, 0xfb, 0xa2, 0xb9, 0x31, 0x33, 0xdf,
	0x8c, 0x34, 0x7f, 0xdf, 0x27, 0x43, 0x5f, 0x4d, 0x52, 0x91, 0xc7, 0xc3, 0xb2, 0x92, 0x5a, 0xb2,
	0x6e, 0x2e, 0x94, 0x8a, 0xa7, 0x22, 0xfc, 0x17, 0xdc, 0x77, 0x22, 0xc9, 0xe2, 0x2b, 0xa1, 0xd9,
	0x1f, 0xe0, 0xe4, 0x68, 0xfb, 0x56, 0x60, 0x47, 0xbd, 0xd1, 0xfe, 0xb0, 0x4e, 0x1a, 0x52, 0x06,
	0x37, 0xc1, 0xf0, 0x8b, 0x05, 0x0e, 0x01, 0x6c, 0x00, 0xf6, 0xbd, 0x58, 0xf8, 0x56, 0x60, 0x45,
	0x7d, 0x8e, 0x26, 0xfb, 0x1b, 0x0e, 0x75, 0x96, 0x0b, 0xa5, 0xe3, 0xbc, 0x1c, 0x2b, 0x31, 0x91,
	0x45, 0xa2, 0xfc, 0x56, 0x60, 0x45, 0x36, 0x1f, 0x34, 0x81, 0x2b, 0x83, 0xb3, 0x08, 0x9c, 0x32,
	0x95, 0x5a, 0xfa, 0x76, 0x60, 0x45, 0xbd, 0x11, 0x6b, 0xca, 0x5d, 0x22, 0x7a, 0x5e, 0xdc, 0x49,
	0x6e, 0x12, 0xd8, 0x9f, 0xd0, 0xbe, 0xcb, 0x66, 0xc2, 0x6f, 0x53, 0x5f, 0x87, 0x4d, 0xe2, 0xab,
	0x6c, 0x26, 0x28, 0x8f, 0xc2, 0x8c, 0x41, 0xbb, 0x88, 0x73, 0xe1, 0x3b, 0x81, 0x15, 0x79, 0x9c,
	0x6c, 0xc4, 0x74, 0x3c, 0x55, 0x7e, 0x37, 0xb0, 0x11, 0x43, 0x3b, 0xfc, 0xd6, 0x02, 0xaf, 0xa9,
	0xb1, 0xbd, 0x67, 0x6b, 0x47, 0xcf, 0x47, 0xe0, 0x26, 0xb1, 0x16, 0x88, 0xfb, 0x40, 0x65, 0x1a,
	0x1f, 0x4b, 0xe5, 0xf1, 0xbd, 0xa0, 0x79, 0x3d, 0x4e, 0x36, 0xfb, 0x05, 0x9c, 0x5c, 0x26, 0x62,
	0x46, 0x33, 0x7a, 0xdc, 0x38, 0xec, 0x1f, 0x70, 0xe3, 0x52, 0x54, 0x7a, 0x5e, 0xe1, 0x4c, 0xd6,
	0xc3, 0x99, 0xaa, 0x78, 0xa2, 0x33, 0x59, 0xf0, 0x26, 0x85, 0x9d, 0xc1, 0x9e, 0xf8, 0x50, 0x4a,
	0x35, 0xaf, 0xc4, 0x98, 0x2a, 0x3b, 0xbb, 0x9e, 0xe9, 0x2f, 0xf3, 0xae, 0xb1, 0xa1, 0xff, 0xa1,
	0x7f, 0x27, 0x27, 0xf1, 0x6c, 0x3c, 0x13, 0xc5, 0x54, 0xa7, 0x7e, 0x67, 0xd7, 0x63, 0x3d, 0x4a,
	0x7b, 0x4b, 0x59, 0x78, 0xd5, 0x4c, 0x49, 0xbf, 0x1b, 0x58, 0x91, 0xc3, 0xd1, 0xc4, 0x21, 0xde,
	0x67, 0x89, 0x4e, 0x7d, 0x97, 0x30, 0xe3, 0xb0, 0x5f, 0xa1, 0x93, 0x8a, 0x6c, 0x9a, 0x6a, 0xdf,
	0x23, 0xb8, 0xf6, 0xc2, 0xcf, 0x16, 0xb8, 0xcb, 0xc3, 0xe0, 0xbe, 0xf0, 0x34, 0x74, 0x16, 0xcb,
	0xec, 0x6b, 0xe9, 0xe3, 0x55, 0xf5, 0xa2, 0x34, 0xfb, 0xda, 0xdf, 0xb8, 0xea, 0xf5, 0xa2, 0x14,
	0x9c, 0xc2, 0x58, 0x27, 0x4f, 0x4e, 0xd5, 0x3c, 0xa7, 0x1d, 0xf6, 0x79, 0xed, 0xb1, 0x63, 0xf0,
	0x54, 0x1a, 0x8f, 0x4e, 0xcf, 0x30, 0xd4, 0xa6, 0xd0, 0x0a, 0x60, 0x21, 0xec, 0xa9, 0xec, 0xa3,
	0x18, 0x67, 0xc5, 0xf8, 0x76, 0xa1, 0x85, 0xa2, 0x9d, 0xd9, 0xbc, 0x87, 0xe0, 0x79, 0xf1, 0x0c,
	0xa1, 0xf0, 0x02, 0xdc, 0xe5, 0x0a, 0xf0, 0x6d, 0xc5, 0x3c, 0x17, 0x55, 0xac, 0x65, 0x45, 0x9d,
	0x3a, 0x7c, 0x05, 0xb0, 0x00, 0x7a, 0x89, 0x28, 0x64, 0x9e, 0x15, 0x14, 0x6f, 0x51, 0x7c, 0x1d,
	0x42, 0x1d, 0x11, 0xa5, 0x6a, 0x1d, 0x19, 0x62, 0x6f, 0xea, 0x88, 0x32, 0x6a, 0x52, 0x87, 0x9f,
	0xda, 0xe0, 0x10, 0xb0, 0xae, 0x23, 0xcf, 0xe8, 0x88, 0x41, 0xbb, 0x8c, 0x75, 0xba, 0xa4, 0x12,
	0xda, 0xec, 0x37, 0xea, 0xb0, 0x9e, 0xc6, 0xa6, 0x69, 0xdc, 0x62, 0x9e, 0xd3, 0x28, 0x18, 0x9c,
	0x2b, 0x51, 0x8d, 0xd3, 0x2c, 0x31, 0xf4, 0x70, 0xb9, 0x8b, 0xc0, 0x9b, 0x2c, 0x59, 0xdf, 0x60,
	0x67, 0xf7, 0x06, 0xbb, 0x9b, 0x1b, 0x7c, 0x02, 0x50, 0x56, 0x12, 0x39, 0x98, 0x09, 0x55, 0xd3,
	0xf4, 0xf7, 0x87, 0xa3, 0x98, 0xdf, 0xcb, 0x26, 0x8b, 0xaf, 0x3d, 0x71, 0xf4, 0xb5, 0x05, 0x07,
	0x1b, 0x71, 0x16, 0xc1, 0x40, 0x94, 0x72, 0x92, 0xe2, 0x59, 0x1e, 0x4a, 0x6d, 0x9f, 0xf0, 0xf3,
	0x62, 0x29, 0xb4, 0x86, 0x73, 0xad, 0xed, 0x9c, 0xb3, 0xd7, 0x39, 0xd7, 0x48, 0xaf, 0xbd, 0x4d,
	0x7a, 0xce, 0x2e, 0xe9, 0x75, 0x1e, 0x21, 0xbd, 0xee, 0xe3, 0xa4, 0xe7, 0xfe, 0x88, 0xf4, 0xbc,
	0x46, 0x7a, 0xe1, 0x0d, 0x1c, 0x3c, 0x97, 0x79, 0x19, 0x57, 0x99, 0x92, 0xc5, 0xcb, 0x42, 0x57,
	0x0b, 0xdc, 0x01, 0x11, 0xe8, 0xbf, 0x9a, 0x30, 0xb5, 0xd7, 0xe0, 0xa3, 0x9a, 0x35, 0xb5, 0x87,
	0x7b, 0x50, 0x13, 0x59, 0x89, 0x7a, 0x65, 0xc6, 0x09, 0x39, 0xc0, 0xea, 0xc5, 0x98, 0x43, 0xfb,
	0xaf, 0x8f, 0x61, 0x1c, 0x36, 0x04, 0x47, 0x60, 0x49, 0xbf, 0x45, 0x3c, 0xf6, 0x9b, 0xee, 0x37,
	0x5a, 0xe2, 0x26, 0x2d, 0x7c, 0x01, 0x7b, 0xab, 0x08, 0x0a, 0xe1, 0x04, 0x60, 0xd2, 0x00, 0xb5,
	0x1a, 0x7e, 0xde, 0xf2, 0x16, 0xbe, 0x96, 0xf6, 0xd7, 0xb1, 0xf9, 0x7c, 0xe0, 0x17, 0x80, 0x75,
	0xc1, 0xbe, 0xb8, 0x7c, 0x3d, 0xf8, 0x09, 0x0d, 0xfe, 0xf4, 0x66, 0x60, 0xdd, 0x76, 0xe8, 0xff,
	0xeb, 0xe4, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x46, 0xb3, 0x5f, 0xcf, 0x06, 0x00, 0x00,
}
