// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	schema.proto

It has these top-level messages:
	Media
	PhotoInfo
	FileInfo
	MediaSet
	Photo
	Fraction
	PhotoSet
	ComparisonEntry
	Comparison
	ComparisonSet
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileType int32

const (
	FileType_JPG FileType = 0
	FileType_RAW FileType = 1
)

var FileType_name = map[int32]string{
	0: "JPG",
	1: "RAW",
}
var FileType_value = map[string]int32{
	"JPG": 0,
	"RAW": 1,
}

func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}
func (FileType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Media struct {
	Photo   *PhotoInfo  `protobuf:"bytes,1,opt,name=photo" json:"photo,omitempty"`
	Name    string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	File    []*FileInfo `protobuf:"bytes,3,rep,name=file" json:"file,omitempty"`
	Deleted bool        `protobuf:"varint,4,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *Media) Reset()                    { *m = Media{} }
func (m *Media) String() string            { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()               {}
func (*Media) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Media) GetPhoto() *PhotoInfo {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *Media) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Media) GetFile() []*FileInfo {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Media) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

// Information about the original media capture, this information shouldn't change.
type PhotoInfo struct {
	DatetimeSecondsSinceEpoch int64     `protobuf:"varint,1,opt,name=datetime_seconds_since_epoch,json=datetimeSecondsSinceEpoch" json:"datetime_seconds_since_epoch,omitempty"`
	Make                      string    `protobuf:"bytes,2,opt,name=make" json:"make,omitempty"`
	Model                     string    `protobuf:"bytes,3,opt,name=model" json:"model,omitempty"`
	Aperture                  *Fraction `protobuf:"bytes,4,opt,name=aperture" json:"aperture,omitempty"`
	ExposureTime              *Fraction `protobuf:"bytes,5,opt,name=exposure_time,json=exposureTime" json:"exposure_time,omitempty"`
	FocalLength               *Fraction `protobuf:"bytes,6,opt,name=focal_length,json=focalLength" json:"focal_length,omitempty"`
	Iso                       int32     `protobuf:"varint,7,opt,name=iso" json:"iso,omitempty"`
	Width                     int32     `protobuf:"varint,8,opt,name=width" json:"width,omitempty"`
	Height                    int32     `protobuf:"varint,9,opt,name=height" json:"height,omitempty"`
}

func (m *PhotoInfo) Reset()                    { *m = PhotoInfo{} }
func (m *PhotoInfo) String() string            { return proto.CompactTextString(m) }
func (*PhotoInfo) ProtoMessage()               {}
func (*PhotoInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PhotoInfo) GetDatetimeSecondsSinceEpoch() int64 {
	if m != nil {
		return m.DatetimeSecondsSinceEpoch
	}
	return 0
}

func (m *PhotoInfo) GetMake() string {
	if m != nil {
		return m.Make
	}
	return ""
}

func (m *PhotoInfo) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *PhotoInfo) GetAperture() *Fraction {
	if m != nil {
		return m.Aperture
	}
	return nil
}

func (m *PhotoInfo) GetExposureTime() *Fraction {
	if m != nil {
		return m.ExposureTime
	}
	return nil
}

func (m *PhotoInfo) GetFocalLength() *Fraction {
	if m != nil {
		return m.FocalLength
	}
	return nil
}

func (m *PhotoInfo) GetIso() int32 {
	if m != nil {
		return m.Iso
	}
	return 0
}

func (m *PhotoInfo) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *PhotoInfo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type FileInfo struct {
	Filename    string   `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Type        FileType `protobuf:"varint,2,opt,name=type,enum=message.FileType" json:"type,omitempty"`
	Md5Sum      []byte   `protobuf:"bytes,3,opt,name=md5sum,proto3" json:"md5sum,omitempty"`
	Sha256Sum   []byte   `protobuf:"bytes,4,opt,name=sha256sum,proto3" json:"sha256sum,omitempty"`
	SizeInBytes int64    `protobuf:"varint,5,opt,name=size_in_bytes,json=sizeInBytes" json:"size_in_bytes,omitempty"`
}

func (m *FileInfo) Reset()                    { *m = FileInfo{} }
func (m *FileInfo) String() string            { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()               {}
func (*FileInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FileInfo) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileInfo) GetType() FileType {
	if m != nil {
		return m.Type
	}
	return FileType_JPG
}

func (m *FileInfo) GetMd5Sum() []byte {
	if m != nil {
		return m.Md5Sum
	}
	return nil
}

func (m *FileInfo) GetSha256Sum() []byte {
	if m != nil {
		return m.Sha256Sum
	}
	return nil
}

func (m *FileInfo) GetSizeInBytes() int64 {
	if m != nil {
		return m.SizeInBytes
	}
	return 0
}

type MediaSet struct {
	Media []*Media `protobuf:"bytes,1,rep,name=media" json:"media,omitempty"`
}

func (m *MediaSet) Reset()                    { *m = MediaSet{} }
func (m *MediaSet) String() string            { return proto.CompactTextString(m) }
func (*MediaSet) ProtoMessage()               {}
func (*MediaSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MediaSet) GetMedia() []*Media {
	if m != nil {
		return m.Media
	}
	return nil
}

type Photo struct {
	Key        string                 `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Path       string                 `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	NumBytes   int64                  `protobuf:"varint,3,opt,name=num_bytes,json=numBytes" json:"num_bytes,omitempty"`
	UserHide   bool                   `protobuf:"varint,5,opt,name=user_hide,json=userHide" json:"user_hide,omitempty"`
	Md5Sum     []byte                 `protobuf:"bytes,6,opt,name=md5sum,proto3" json:"md5sum,omitempty"`
	Sha256Sum  []byte                 `protobuf:"bytes,7,opt,name=sha256sum,proto3" json:"sha256sum,omitempty"`
	Properties *Photo_PhotoProperties `protobuf:"bytes,4,opt,name=properties" json:"properties,omitempty"`
}

func (m *Photo) Reset()                    { *m = Photo{} }
func (m *Photo) String() string            { return proto.CompactTextString(m) }
func (*Photo) ProtoMessage()               {}
func (*Photo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Photo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Photo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Photo) GetNumBytes() int64 {
	if m != nil {
		return m.NumBytes
	}
	return 0
}

func (m *Photo) GetUserHide() bool {
	if m != nil {
		return m.UserHide
	}
	return false
}

func (m *Photo) GetMd5Sum() []byte {
	if m != nil {
		return m.Md5Sum
	}
	return nil
}

func (m *Photo) GetSha256Sum() []byte {
	if m != nil {
		return m.Sha256Sum
	}
	return nil
}

func (m *Photo) GetProperties() *Photo_PhotoProperties {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Photo_PhotoProperties struct {
	EpochInSeconds int64     `protobuf:"varint,1,opt,name=epoch_in_seconds,json=epochInSeconds" json:"epoch_in_seconds,omitempty"`
	Width          int32     `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	Height         int32     `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Make           string    `protobuf:"bytes,4,opt,name=make" json:"make,omitempty"`
	Model          string    `protobuf:"bytes,5,opt,name=model" json:"model,omitempty"`
	Aperture       *Fraction `protobuf:"bytes,6,opt,name=aperture" json:"aperture,omitempty"`
	ExposureTime   *Fraction `protobuf:"bytes,7,opt,name=exposure_time,json=exposureTime" json:"exposure_time,omitempty"`
	FocalLength    *Fraction `protobuf:"bytes,8,opt,name=focal_length,json=focalLength" json:"focal_length,omitempty"`
	Iso            int32     `protobuf:"varint,9,opt,name=iso" json:"iso,omitempty"`
}

func (m *Photo_PhotoProperties) Reset()                    { *m = Photo_PhotoProperties{} }
func (m *Photo_PhotoProperties) String() string            { return proto.CompactTextString(m) }
func (*Photo_PhotoProperties) ProtoMessage()               {}
func (*Photo_PhotoProperties) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *Photo_PhotoProperties) GetEpochInSeconds() int64 {
	if m != nil {
		return m.EpochInSeconds
	}
	return 0
}

func (m *Photo_PhotoProperties) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Photo_PhotoProperties) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Photo_PhotoProperties) GetMake() string {
	if m != nil {
		return m.Make
	}
	return ""
}

func (m *Photo_PhotoProperties) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Photo_PhotoProperties) GetAperture() *Fraction {
	if m != nil {
		return m.Aperture
	}
	return nil
}

func (m *Photo_PhotoProperties) GetExposureTime() *Fraction {
	if m != nil {
		return m.ExposureTime
	}
	return nil
}

func (m *Photo_PhotoProperties) GetFocalLength() *Fraction {
	if m != nil {
		return m.FocalLength
	}
	return nil
}

func (m *Photo_PhotoProperties) GetIso() int32 {
	if m != nil {
		return m.Iso
	}
	return 0
}

type Fraction struct {
	Numerator   int32 `protobuf:"varint,1,opt,name=numerator" json:"numerator,omitempty"`
	Denominator int32 `protobuf:"varint,2,opt,name=denominator" json:"denominator,omitempty"`
}

func (m *Fraction) Reset()                    { *m = Fraction{} }
func (m *Fraction) String() string            { return proto.CompactTextString(m) }
func (*Fraction) ProtoMessage()               {}
func (*Fraction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Fraction) GetNumerator() int32 {
	if m != nil {
		return m.Numerator
	}
	return 0
}

func (m *Fraction) GetDenominator() int32 {
	if m != nil {
		return m.Denominator
	}
	return 0
}

type PhotoSet struct {
	Photo []*Photo `protobuf:"bytes,1,rep,name=photo" json:"photo,omitempty"`
}

func (m *PhotoSet) Reset()                    { *m = PhotoSet{} }
func (m *PhotoSet) String() string            { return proto.CompactTextString(m) }
func (*PhotoSet) ProtoMessage()               {}
func (*PhotoSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PhotoSet) GetPhoto() []*Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

type ComparisonEntry struct {
	Photo1 string `protobuf:"bytes,1,opt,name=photo1" json:"photo1,omitempty"`
	Photo2 string `protobuf:"bytes,2,opt,name=photo2" json:"photo2,omitempty"`
	// Should only be 1 or 2.
	Score int32 `protobuf:"varint,3,opt,name=score" json:"score,omitempty"`
}

func (m *ComparisonEntry) Reset()                    { *m = ComparisonEntry{} }
func (m *ComparisonEntry) String() string            { return proto.CompactTextString(m) }
func (*ComparisonEntry) ProtoMessage()               {}
func (*ComparisonEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ComparisonEntry) GetPhoto1() string {
	if m != nil {
		return m.Photo1
	}
	return ""
}

func (m *ComparisonEntry) GetPhoto2() string {
	if m != nil {
		return m.Photo2
	}
	return ""
}

func (m *ComparisonEntry) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type Comparison struct {
	Epoch int64              `protobuf:"varint,1,opt,name=epoch" json:"epoch,omitempty"`
	Entry []*ComparisonEntry `protobuf:"bytes,2,rep,name=entry" json:"entry,omitempty"`
}

func (m *Comparison) Reset()                    { *m = Comparison{} }
func (m *Comparison) String() string            { return proto.CompactTextString(m) }
func (*Comparison) ProtoMessage()               {}
func (*Comparison) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Comparison) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Comparison) GetEntry() []*ComparisonEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type ComparisonSet struct {
	Comparison []*Comparison `protobuf:"bytes,1,rep,name=comparison" json:"comparison,omitempty"`
}

func (m *ComparisonSet) Reset()                    { *m = ComparisonSet{} }
func (m *ComparisonSet) String() string            { return proto.CompactTextString(m) }
func (*ComparisonSet) ProtoMessage()               {}
func (*ComparisonSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ComparisonSet) GetComparison() []*Comparison {
	if m != nil {
		return m.Comparison
	}
	return nil
}

func init() {
	proto.RegisterType((*Media)(nil), "message.Media")
	proto.RegisterType((*PhotoInfo)(nil), "message.PhotoInfo")
	proto.RegisterType((*FileInfo)(nil), "message.FileInfo")
	proto.RegisterType((*MediaSet)(nil), "message.MediaSet")
	proto.RegisterType((*Photo)(nil), "message.Photo")
	proto.RegisterType((*Photo_PhotoProperties)(nil), "message.Photo.PhotoProperties")
	proto.RegisterType((*Fraction)(nil), "message.Fraction")
	proto.RegisterType((*PhotoSet)(nil), "message.PhotoSet")
	proto.RegisterType((*ComparisonEntry)(nil), "message.ComparisonEntry")
	proto.RegisterType((*Comparison)(nil), "message.Comparison")
	proto.RegisterType((*ComparisonSet)(nil), "message.ComparisonSet")
	proto.RegisterEnum("message.FileType", FileType_name, FileType_value)
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x6e, 0xeb, 0x44,
	0x10, 0xc6, 0x71, 0x9c, 0x38, 0x93, 0xb4, 0x0d, 0x0b, 0x42, 0xa6, 0x54, 0x28, 0xb2, 0x40, 0x8a,
	0x90, 0x88, 0x20, 0xa5, 0xbd, 0x04, 0xf1, 0x53, 0xa0, 0x15, 0x48, 0xd5, 0xb6, 0x52, 0x2f, 0x2d,
	0xd7, 0x9e, 0xd6, 0xab, 0xc6, 0xbb, 0x96, 0x77, 0x23, 0x08, 0x0f, 0xc0, 0x83, 0x70, 0xc3, 0x7b,
	0x9c, 0x57, 0x38, 0x2f, 0x74, 0x34, 0xeb, 0x8d, 0x93, 0x46, 0xcd, 0xc5, 0xe9, 0x4d, 0x34, 0x3f,
	0xdf, 0x7a, 0x67, 0xe6, 0xfb, 0x66, 0x03, 0x23, 0x9d, 0x15, 0x58, 0xa6, 0xb3, 0xaa, 0x56, 0x46,
	0xb1, 0x7e, 0x89, 0x5a, 0xa7, 0x8f, 0x18, 0xff, 0xeb, 0x41, 0xf0, 0x27, 0xe6, 0x22, 0x65, 0x53,
	0x08, 0xaa, 0x42, 0x19, 0x15, 0x79, 0x13, 0x6f, 0x3a, 0x9c, 0xb3, 0x99, 0x83, 0xcc, 0xae, 0x29,
	0x7a, 0x29, 0x1f, 0x14, 0x6f, 0x00, 0x8c, 0x41, 0x57, 0xa6, 0x25, 0x46, 0x9d, 0x89, 0x37, 0x1d,
	0x70, 0x6b, 0xb3, 0x2f, 0xa1, 0xfb, 0x20, 0x16, 0x18, 0xf9, 0x13, 0x7f, 0x3a, 0x9c, 0x7f, 0xd8,
	0x1e, 0xfe, 0x55, 0x2c, 0xd0, 0x9e, 0xb5, 0x69, 0x16, 0x41, 0x3f, 0xc7, 0x05, 0x1a, 0xcc, 0xa3,
	0xee, 0xc4, 0x9b, 0x86, 0x7c, 0xed, 0xc6, 0x6f, 0x3b, 0x30, 0x68, 0x6f, 0x62, 0x3f, 0xc0, 0x49,
	0x9e, 0x1a, 0x34, 0xa2, 0xc4, 0x44, 0x63, 0xa6, 0x64, 0xae, 0x13, 0x2d, 0x64, 0x86, 0x09, 0x56,
	0x2a, 0x2b, 0x6c, 0x8d, 0x3e, 0xff, 0x74, 0x8d, 0xb9, 0x69, 0x20, 0x37, 0x84, 0xb8, 0x20, 0x00,
	0xd5, 0x58, 0xa6, 0x4f, 0x6d, 0x8d, 0x64, 0xb3, 0x8f, 0x21, 0x28, 0x55, 0x8e, 0x8b, 0xc8, 0xb7,
	0xc1, 0xc6, 0x61, 0x5f, 0x43, 0x98, 0x56, 0x58, 0x9b, 0x65, 0x8d, 0xb6, 0xa6, 0x67, 0xd5, 0xd7,
	0x69, 0x66, 0x84, 0x92, 0xbc, 0x85, 0xb0, 0x73, 0x38, 0xc0, 0xbf, 0x2b, 0xa5, 0x97, 0x35, 0x26,
	0x74, 0x75, 0x14, 0xec, 0x3b, 0x33, 0x5a, 0xe3, 0x6e, 0x45, 0x89, 0xec, 0x3b, 0x18, 0x3d, 0xa8,
	0x2c, 0x5d, 0x24, 0x0b, 0x94, 0x8f, 0xa6, 0x88, 0x7a, 0xfb, 0x8e, 0x0d, 0x2d, 0xec, 0x0f, 0x8b,
	0x62, 0x63, 0xf0, 0x85, 0x56, 0x51, 0x7f, 0xe2, 0x4d, 0x03, 0x4e, 0x26, 0x35, 0xf1, 0x97, 0xc8,
	0x4d, 0x11, 0x85, 0x36, 0xd6, 0x38, 0xec, 0x13, 0xe8, 0x15, 0x28, 0x1e, 0x0b, 0x13, 0x0d, 0x6c,
	0xd8, 0x79, 0xf1, 0xff, 0x1e, 0x84, 0x6b, 0x0a, 0xd8, 0x31, 0x84, 0x44, 0x82, 0xe5, 0xce, 0xb3,
	0x23, 0x68, 0x7d, 0xe2, 0xcf, 0xac, 0xaa, 0x66, 0x5e, 0x87, 0x3b, 0xfc, 0xdd, 0xae, 0x2a, 0xe4,
	0x36, 0x4d, 0xf7, 0x94, 0xf9, 0x99, 0x5e, 0x96, 0x76, 0x86, 0x23, 0xee, 0x3c, 0x76, 0x02, 0x03,
	0x5d, 0xa4, 0xf3, 0xb3, 0x73, 0x4a, 0x75, 0x6d, 0x6a, 0x13, 0x60, 0x31, 0x1c, 0x68, 0xf1, 0x0f,
	0x26, 0x42, 0x26, 0xf7, 0x2b, 0x83, 0xda, 0xce, 0xcc, 0xe7, 0x43, 0x0a, 0x5e, 0xca, 0x9f, 0x28,
	0x14, 0x7f, 0x03, 0xa1, 0xd5, 0xe1, 0x0d, 0x1a, 0xf6, 0x05, 0x04, 0x25, 0xd9, 0x91, 0x67, 0xd5,
	0x74, 0xd8, 0x56, 0x63, 0x11, 0xbc, 0x49, 0xc6, 0xff, 0x75, 0x21, 0xb0, 0x8a, 0xa1, 0x29, 0x3d,
	0xe1, 0xca, 0xf5, 0x44, 0x26, 0xd1, 0x5f, 0xa5, 0xa6, 0x58, 0xd3, 0x4f, 0x36, 0xfb, 0x0c, 0x06,
	0x72, 0x59, 0xba, 0x0a, 0x7c, 0x5b, 0x41, 0x28, 0x97, 0xa5, 0xbd, 0x9e, 0x92, 0x4b, 0x8d, 0x75,
	0x52, 0x88, 0xbc, 0xa1, 0x34, 0xe4, 0x21, 0x05, 0x7e, 0x17, 0xf9, 0x76, 0xd7, 0xbd, 0xfd, 0x5d,
	0xf7, 0x77, 0xbb, 0xfe, 0x1e, 0xa0, 0xaa, 0x15, 0xe9, 0x46, 0xa0, 0x76, 0xd2, 0xfa, 0xfc, 0xf9,
	0x56, 0x35, 0xbf, 0xd7, 0x2d, 0x8a, 0x6f, 0x9d, 0x38, 0x7e, 0xd3, 0x81, 0xa3, 0x9d, 0x3c, 0x9b,
	0xc2, 0xd8, 0x2e, 0x00, 0x8d, 0xd2, 0xed, 0x85, 0xdb, 0x85, 0x43, 0x1b, 0xbf, 0x94, 0x6e, 0x15,
	0x36, 0x3a, 0xe9, 0xbc, 0xac, 0x13, 0x7f, 0x5b, 0x27, 0xed, 0xba, 0x74, 0x5f, 0x5a, 0x97, 0x60,
	0xdf, 0xba, 0xf4, 0x5e, 0xb1, 0x2e, 0xfd, 0xd7, 0xad, 0x4b, 0xf8, 0x3e, 0xeb, 0x32, 0x68, 0xd7,
	0x25, 0xbe, 0x82, 0x70, 0x0d, 0x25, 0xba, 0xe4, 0xb2, 0xc4, 0x3a, 0x35, 0xaa, 0xb6, 0x53, 0x0b,
	0xf8, 0x26, 0xc0, 0x26, 0x30, 0xcc, 0x51, 0xaa, 0x52, 0x48, 0x9b, 0x6f, 0xc6, 0xb6, 0x1d, 0x22,
	0x89, 0x5a, 0x3e, 0x9c, 0x44, 0xd7, 0xaf, 0xe5, 0x73, 0x89, 0x5a, 0x84, 0x7b, 0x29, 0xe3, 0x3b,
	0x38, 0xfa, 0x59, 0x95, 0x55, 0x5a, 0x0b, 0xad, 0xe4, 0x85, 0x34, 0xf5, 0x8a, 0x18, 0xb0, 0xb9,
	0x6f, 0x9d, 0x5c, 0x9d, 0xd7, 0xc6, 0xe7, 0x4e, 0xb3, 0xce, 0x23, 0x16, 0x74, 0xa6, 0x6a, 0x74,
	0x84, 0x35, 0x4e, 0xcc, 0x01, 0x36, 0x1f, 0x26, 0xcc, 0xf6, 0xb3, 0xd8, 0x38, 0x6c, 0x06, 0x01,
	0xd2, 0x95, 0x51, 0xc7, 0x96, 0x18, 0xb5, 0x25, 0xee, 0x94, 0xc4, 0x1b, 0x58, 0xfc, 0x0b, 0x1c,
	0x6c, 0x32, 0xd4, 0xe3, 0x29, 0x40, 0xd6, 0x06, 0x5c, 0xa3, 0x1f, 0xbd, 0xf0, 0x15, 0xbe, 0x05,
	0xfb, 0xea, 0xa4, 0x79, 0x70, 0xe8, 0xcd, 0x60, 0x7d, 0xf0, 0xaf, 0xae, 0x7f, 0x1b, 0x7f, 0x40,
	0x06, 0xff, 0xf1, 0x6e, 0xec, 0xdd, 0xf7, 0xec, 0xdf, 0xcf, 0xe9, 0xbb, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x70, 0xd8, 0xf8, 0x6f, 0x8e, 0x06, 0x00, 0x00,
}
